### ISSUE TITLE
Missing command using npx

### ISSUE THREAD

**Issue by jamesholcomb** [Shaddix/react-native-bootsplash-cli-fork#2]
Thought I would give this a shot (copied from the README)...

```sh
15:37 $ npx react-native generate-bootsplash-fork --help
error Unrecognized command "generate-bootsplash-fork". Did you mean "generate-bootsplash"?
info Run "react-native --help" to see a list of all available commands.

**Comment by Shaddix** [comment]
Have you ran `npm install --save-dev react-native-bootsplash-cli-fork` first?

Currently running with `npx` still requires local package installation. I'll investigate the possibility to run via `npx` without it, but at the moment the installation step is required.

**Comment by jamesholcomb** [comment]
That was indeed the issue 👍
