### ISSUE TITLE
Error Cli

### ISSUE THREAD

**Issue by tastafur** [Shaddix/react-native-bootsplash-cli-fork#3]
I have tried to generate it from an existing project and it fails, I don't know if it will go from a project without having launched the enerate-bootsplash before

`yarn react-native generate-bootsplash-fork src/assets/bootsplash_logo_original.png \
  --background-color=F3F3F3 \
  --dark-logo=src/assets/bootsplash_logo_original.png \
  --assets-path=src/assets \
--dark-background-color=222222
`

**Comment by Shaddix** [comment]
what error you are actually getting? What version of `react-native-bootsplash` you are using?

**Comment by tastafur** [comment]
i am getting this error and i am using version 4.3.2
![Captura de Pantalla 2022-08-17 a las 17 32 06](https://user-images.githubusercontent.com/11853181/185180761-b5e9db5c-977f-44ef-9d74-c59bf3781b64.png)
and refers to this point in the code
![Captura de Pantalla 2022-08-17 a las 17 32 43](https://user-images.githubusercontent.com/11853181/185180903-a2cf9f02-3a67-46fe-a834-b82175a407f8.png)

**Comment by Shaddix** [comment]
could you please try the latest version of react-native-bootsplash-cli-fork (4.3.2) which was just pushed?

**Comment by tastafur** [comment]
Now it works well

**Comment by tastafur** [comment]
Thanks @Shaddix very much!

**Comment by Shaddix** [comment]
Thanks for reporting!
